language: node_js

arch:
  - arm64
# whitelisted branches
branches:
  only:
    - master
    - next
node_js:
  - "12.16.3"
cache:
  npm: true
services:
  - mysql
  - docker

scripts:
- docker build . -f Dockerfile.aarch64 -t packyzbq/konga:0.14.9-arm64
- docker login -u $ACS_USERNAME -p $ACS_PASSWORD
- docker push packyzbq/konga:0.14.9-arm64

